apiVersion: v1
kind: Service
metadata:
    name: "xwiki-b7dd"
    labels:
        app: "xwiki-b7dd"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "xwiki-b7dd"